import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    handle: "divya-madhunashni-vati-extra-power",
    title: "DIVYA MADHUNASHNI VATI EXTRA POWER",
    description: "A powerful, time-tested Ayurvedic formulation designed to help maintain healthy blood sugar levels naturally.",
    longDescription: "Divya Madhunashni Vati Extra Power is a powerful, time-tested Ayurvedic formulation designed to help maintain healthy blood sugar levels naturally. Made with a synergistic blend of rare anti-diabetic herbs, it supports optimal pancreatic function, improves glucose metabolism, and reduces insulin resistance.",
    vendor: "Divya Pharmacy",
    category: "DIABETES CARE",
    type: "Tablet",
    tags: ["ayurvedic", "diabetes", "blood sugar"],
    price: 299,
    compareAtPrice: 399,
    image: "https://www.patanjaliayurved.net/assets/product_images/400x500/1764139919madhu1.webp",
    benefits: ["Controls blood sugar", "Supports insulin function", "Reduces sugar cravings"],
    ingredients: ["Karela", "Jamun Beej", "Gurmar", "Methi"],
    usage: "2 tablets twice daily, 30 minutes before meals with warm water."
  },
  {
    handle: "divya-swasari-pravahi",
    title: "DIVYA SWASARI PRAVAHI",
    description: "Premium herbal tonic for comprehensive respiratory health. Soothes irritated airways and clears bronchial congestion.",
    longDescription: "Divya Swasari Pravahi is a premium herbal tonic for comprehensive respiratory health. This carefully crafted liquid Ayurvedic formulation soothes irritated airways, provides relief from chronic cough, clears bronchial congestion, and strengthens the lungs.",
    vendor: "Divya Pharmacy",
    category: "RESPIRATORY",
    type: "Liquid",
    tags: ["ayurvedic", "respiratory", "cough relief"],
    price: 189,
    compareAtPrice: 250,
    image: "https://www.bbassets.com/media/uploads/p/l/40016327_4-patanjali-divya-swasari-pravahi.jpg",
    benefits: ["Relieves cough", "Clears respiratory tract", "Supports lung function"],
    ingredients: ["Vasaka", "Tulsi", "Mulethi"],
    usage: "10–15 ml twice daily, mixed in warm water."
  },
  {
    handle: "divya-swasari-gold-60",
    title: "DIVYA SWASARI GOLD 60 TABLETS",
    description: "Superior Ayurvedic tablet enriched with Swarna Bhasma for deep, lasting relief from chronic respiratory conditions.",
    longDescription: "Divya Swasari Gold is a superior Ayurvedic tablet enriched with the revered Swarna Bhasma (purified gold ash). This premium formulation delivers deep, lasting relief from chronic respiratory conditions including asthma and persistent cough.",
    vendor: "Divya Pharmacy",
    category: "RESPIRATORY",
    type: "Tablet",
    tags: ["ayurvedic", "respiratory", "gold bhasma"],
    price: 399,
    compareAtPrice: 499,
    image: "https://core.mymedicalshop.com/media/products/E3A5C5Cproduct5C5Cp5C5Ca5C5Cpatanjali_divya_swasari_gold_60_n_-_t_1_52ea1ce7.jpeg",
    benefits: ["Enriched with Gold Bhasma", "Strengthens immunity", "Supports lung capacity"],
    ingredients: ["Swarna Bhasma", "Vasaka", "Sitopaladi Churna"],
    usage: "1–2 tablets twice daily with honey or warm water."
  },
  {
    handle: "divya-medha-vati-extra-power",
    title: "DIVYA MEDHA VATI EXTRA POWER",
    description: "Advanced Ayurvedic formulation for mental clarity, concentration, memory enhancement, and stress relief.",
    longDescription: "Divya Medha Vati Extra Power is an advanced Ayurvedic formulation for mental clarity, concentration, memory enhancement, and stress relief. Rooted in the ancient science of Medhya Rasayanas, this powerful tablet nourishes brain cells.",
    vendor: "Divya Pharmacy",
    category: "BRAIN & MEMORY",
    type: "Tablet",
    tags: ["ayurvedic", "brain health", "memory booster"],
    price: 329,
    compareAtPrice: 449,
    image: "https://images.apollo247.in/pub/media/catalog/product/D/I/DIV0264_1-JULY23_1.jpg",
    benefits: ["Improves memory", "Reduces stress", "Supports mental clarity"],
    ingredients: ["Brahmi", "Shankhpushpi", "Ashwagandha"],
    usage: "2 tablets twice daily with warm milk or water."
  },
  {
    handle: "divya-mukta-vati-extra-power",
    title: "DIVYA MUKTA VATI EXTRA POWER",
    description: "India's most trusted Ayurvedic remedy for high blood pressure. Enriched with Mukta (Pearl) Pishti.",
    longDescription: "Divya Mukta Vati Extra Power is India's most trusted Ayurvedic remedy for high blood pressure. Enriched with Mukta (Pearl) Pishti and a synergistic blend of cardioprotective herbs, it gently effectively lowers BP.",
    vendor: "Divya Pharmacy",
    category: "HEART & BP",
    type: "Tablet",
    tags: ["ayurvedic", "blood pressure", "heart health"],
    price: 359,
    compareAtPrice: 499,
    image: "https://www.patanjaliayurved.net/assets/product_images/400x500/17643297541.webp",
    benefits: ["Controls high BP", "Reduces stress", "Improves circulation"],
    ingredients: ["Mukta Pishti", "Brahmi", "Arjuna Chaal"],
    usage: "2 tablets twice daily, 30 minutes before meals."
  },
  {
    handle: "divya-ashwagandha-churna",
    title: "DIVYA ASHWAGANDHA CHURNA",
    description: "Pure, unadulterated Ashwagandha root powder. Naturally boosts energy, builds resilience to stress.",
    longDescription: "Divya Ashwagandha Churna is pure, unadulterated Ashwagandha root powder. Revered as a Rasayana, Ashwagandha naturally boosts energy, builds resilience to stress, and strengthens the immune system.",
    vendor: "Divya Pharmacy",
    category: "COMBOS",
    type: "Powder",
    tags: ["ayurvedic", "ashwagandha", "stress relief"],
    price: 89,
    compareAtPrice: 120,
    image: "https://www.patanjaliayurved.net/assets/product_images/400x500/1764244936ashw1.webp",
    benefits: ["Boosts energy", "Reduces stress", "Strengthens immunity"],
    ingredients: ["Ashwagandha Root Powder"],
    usage: "3–5g with warm milk and honey, twice daily."
  },
  {
    handle: "triphala-churna",
    title: "TRIPHALA CHURNA",
    description: "Ayurveda's most celebrated digestive cleanser. A harmonious blend of three sacred fruits.",
    longDescription: "Triphala Churna is one of Ayurveda's most celebrated formulations — a harmonious blend of three sacred fruits: Amalaki, Bibhitaki, and Haritaki. It is the ultimate digestive cleanser.",
    vendor: "Divya Pharmacy",
    category: "DIGESTIVE",
    type: "Powder",
    tags: ["triphala", "digestive", "detox"],
    price: 69,
    compareAtPrice: 99,
    image: "https://www.santulan.in/wp-content/uploads/2020/04/Triphala-Churna.png",
    benefits: ["Natural digestive cleanser", "Detoxifies colon", "Rich in Vitamin C"],
    ingredients: ["Amalaki", "Bibhitaki", "Haritaki"],
    usage: "3–5g with warm water at bedtime."
  },
  {
    handle: "aastha-dhoop-batti",
    title: "AASTHA DHOOP BATTI",
    description: "Sacred fragrance for your home. Crafted from the finest natural herbs, resins, and essential oils.",
    longDescription: "Aastha Dhoop Batti is crafted from the finest natural ingredients. Unlike synthetic incense, it burns clean, filling your home with a rich, lingering fragrance that purifies the atmosphere.",
    vendor: "Aastha",
    category: "POOJA ESSENTIALS",
    type: "Dhoop",
    tags: ["dhoop batti", "pooja", "incense"],
    price: 49,
    compareAtPrice: 75,
    image: "https://5.imimg.com/data5/SELLER/Default/2021/1/RG/VV/RF/65524077/140-gm-sandal-aastha-wet-dhoop.jpg",
    benefits: ["100% natural", "Long-lasting fragrance", "Purifies atmosphere"],
    ingredients: ["Natural herbs", "Resins", "Essential oils"],
    usage: "Light the tip and place in a holder."
  },
  {
    handle: "aastha-agar-batti",
    title: "AASTHA AGAR BATTI",
    description: "Divine Agar Wood fragrance for daily puja. Purifies the environment and invites positive energy.",
    longDescription: "Aastha Agar Batti brings the rare, precious fragrance of authentic Agar wood to your home. Each stick is hand-crafted using pure Agar wood essence blended with natural herbs.",
    vendor: "Aastha",
    category: "POOJA ESSENTIALS",
    type: "Agarbatti",
    tags: ["agar batti", "puja", "incense"],
    price: 39,
    compareAtPrice: 60,
    image: "https://ayurvedalifeclinic.com/wp-content/uploads/2023/09/1688624625AgarbattiSandal150g1.png",
    benefits: ["Authentic Agar fragrance", "Removes negative energy", "Clean-burning"],
    ingredients: ["Agarwood essence", "Natural herbs"],
    usage: "Light the tip and place in an incense holder."
  },
  {
    handle: "aastha-cows-ghee-puja",
    title: "AASTHA COW'S GHEE",
    description: "Sacred Cow's Ghee for Hawan and Puja. Creates a divine aura and purifies the environment.",
    longDescription: "Aastha Cow's Ghee helps to create a divine aura during Hawan and Puja. It burns without leaving any residue and gives a pleasant smell and blissful environment. \n\nSafety Information: Store in a cool & dry place. Keep away from direct sunlight. Use before 09 months from manufacturing date.",
    vendor: "Aastha",
    category: "POOJA ESSENTIALS",
    type: "Ghee",
    tags: ["cow ghee", "puja", "hawan", "sacred"],
    price: 199,
    compareAtPrice: 250,
    image: "https://www.patanjaliayurved.net/assets/product_images/400x500/1773208352_3214.webp",
    benefits: ["Creates divine aura", "Burns without residue", "Pleasant fragrance"],
    ingredients: ["Pure Cow Ghee"],
    usage: "Use for lighting diyas, Hawan, and other Puja rituals."
  },
  {
    handle: "aastha-pure-cow-ghee",
    title: "AASTHA PURE COW GHEE",
    description: "Sacred & Sattvic Desi Cow Ghee made using the traditional Vedic Bilona method.",
    longDescription: "Aastha Pure Cow Ghee is made from fresh desi cow milk using the traditional Vedic Bilona method. This ancient process preserves all the naturally occurring nutrients and sattvik properties.",
    vendor: "Aastha",
    category: "NEW ARRIVAL",
    type: "Ghee",
    tags: ["desi cow ghee", "pure ghee", "vedic"],
    price: 249,
    compareAtPrice: 320,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop",
    benefits: ["100% Pure Desi Cow Ghee", "Vedic Bilona method", "Rich in vitamins"],
    ingredients: ["Desi Cow Milk"],
    usage: "Use for puja, havan, or cooking.",
    options: [
      { name: "Size", values: ["250ml", "500ml", "1 Litre"] }
    ]
  },
  {
    handle: "divya-peedanil-gold-60",
    title: "DIVYA PEEDANIL GOLD TABLET 60",
    description: "Advanced joint pain formulation enriched with Swarna Bhasma for deep-tissue healing.",
    longDescription: "Divya Peedanil Gold is an advanced, premium Ayurvedic joint pain formulation enriched with the revered Swarna Bhasma. It delivers effective, lasting relief from arthritis and joint stiffness.",
    vendor: "Divya Pharmacy",
    category: "JOINT CARE",
    type: "Tablet",
    tags: ["ayurvedic", "joint pain", "arthritis"],
    price: 349,
    compareAtPrice: 449,
    image: "https://www.patanjaliayurved.net/assets/product_images/400x500/1764149736peedanil20n1.webp",
    benefits: ["Relieves arthritis", "Reduces inflammation", "Improves mobility"],
    ingredients: ["Swarna Bhasma", "Shallaki", "Nirgundi"],
    usage: "1–2 tablets twice daily with warm water."
  }
];

export const CATEGORIES = [
  "DIABETES CARE",
  "RESPIRATORY",
  "BRAIN & MEMORY",
  "HEART & BP",
  "JOINT CARE",
  "DIGESTIVE",
  "POOJA ESSENTIALS",
  "NEW ARRIVAL",
  "COMBOS"
];
